variables:
  LINSTOR_CONTROLLER_HOST: 'linstor-controller'
  LINSTOR_CONTROLLER_PORT: '3370'

before_script:
  # setup ssh access to clone python-linstor dep
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $GIT_HOST >> ~/.ssh/known_hosts
  # now install python-linstor into venv
  - pushd /tmp
  - python -m venv venv
  - git clone --recursive git@$GIT_HOST:$PYTHON_LINSTOR_PATH
  - cd linstor-api-py
  - make gensrc
  - ../venv/bin/python setup.py install
  # and also install xmlrunner package
  - ../venv/bin/pip install xmlrunner
  - popd

services:
  - name: gitlab.linbit:5050/linstor/linstor-server/controller
    alias: linstor-controller

test:2.7:
  stage: test
  image: python:2.7
  before_script:
    # setup ssh access to clone python-linstor dep
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $GIT_HOST >> ~/.ssh/known_hosts
    - pip install virtualenv
    # now install python-linstor into venv
    - pushd /tmp
    - python -m virtualenv venv
    - git clone --recursive git@$GIT_HOST:$PYTHON_LINSTOR_PATH
    - cd linstor-api-py
    - make gensrc
    - ../venv/bin/python setup.py install
    # and also install xmlrunner package
    - ../venv/bin/pip install xmlrunner
    - popd
  script:
    - /tmp/venv/bin/python tests.py
  artifacts:
    reports:
      junit: test-reports/TEST-*.xml

test:3.5:
  stage: test
  image: python:3.5
  script:
    - /tmp/venv/bin/python tests.py
  artifacts:
    reports:
      junit: test-reports/TEST-*.xml

test:3.8:
  stage: test
  image: python:3.8
  script:
    - /tmp/venv/bin/python tests.py
  artifacts:
    reports:
      junit: test-reports/TEST-*.xml
